SABS-R3-Epidemiology/branchpro

.github/workflows/flake8-style-test.yml
.github/workflows/os-unittests.yml
.github/workflows/python-version-unittests.yml
run-tests.py

Addresses some of the points in Issue #1 (link below).
https://github.com/SABS-R3-Epidemiology/branchpro/issues/1

Issue 01 testing

---

.coveragerc
.github/workflows/coverage-test.yml

Trying to setup codecov. Issue #1.

coverage test

---

.github/workflows/check-copyright.yml
.github/workflows/coverage-test.yml
.github/workflows/doctest.yml
.github/workflows/os-unittests.yml
.github/workflows/python-version-unittests.yml
run-tests.py

Issue 01 sphinx doc test

---

.requirements-docs.txt
docs/source/conf.py

Small changes made while connecting to readthedocs.io

Read the docs

---

README.md

Add codecov and docs badges in README

---

branchpro/models.py
branchpro/tests/test_models.py
docs/source/models.rst

Solves issue #23 of varying R profiles. Loads of help from @DavAug

Issue 23 add r step

---

branchpro/models.py
branchpro/tests/test_models.py
docs/source/models.rst

Corrected typos observed by @rcw5890 in #38

Corrected typos observed by #38

---

README.md

add details to readme

---

branchpro/apps/_simulation.py

Fix trace visibility in app plot

---

branchpro/apps/_simulation.py
branchpro/apps/dash_app.py

Use more useful data for the dash app; give more flexibility for the sliders setup

Use proper flu data for year 2020 for the dash app

---

branchpro/apps/_simulation.py
branchpro/apps/_sliders.py
branchpro/tests/test_sliders.py
setup.py

Implement daq slider

---

branchpro/__init__.py
branchpro/apps/__init__.py
branchpro/apps/_reproduction_number_plot.py
branchpro/posterior.py
branchpro/tests/test_posterior.py
branchpro/tests/test_reproduction_number_plot.py
docs/source/apps.rst

Issue 65 inference plot

---

.coveragerc
branchpro/__init__.py
branchpro/apps/__init__.py
branchpro/apps/_inference.py
branchpro/apps/_reproduction_number_plot.py
branchpro/apps/_simulation.py
branchpro/apps/inference_dash_app.py
branchpro/posterior.py
docs/source/apps.rst

Issue 71 inference app

---

branchpro/__init__.py
branchpro/models.py
branchpro/posterior.py
branchpro/tests/test_posterior.py
docs/source/posterior_distribution.rst

Issue 82 extended posterior class

---

branchpro/models.py
branchpro/posterior.py
branchpro/tests/test_posterior.py

Fixes the bug with the use of unnormalised serial intervals as stated in issue #84.

Issue 84 normalization serial interval bug

---

branchpro/apps/_simulation.py
branchpro/apps/_sliders.py
branchpro/apps/simulation_dash_app.py
branchpro/tests/test_sliders.py

Issue 106 107 style

---

branchpro/apps/_incidence_number_plot.py
branchpro/apps/_inference.py
branchpro/apps/_reproduction_number_plot.py
branchpro/apps/_sliders.py
branchpro/apps/inference_dash_app.py
branchpro/posterior.py
branchpro/tests/test_posterior.py
branchpro/tests/test_reproduction_number_plot.py
branchpro/tests/test_sliders.py

Issue 105 extend inf app

---

branchpro/apps/_dash_app.py
branchpro/apps/_inference.py
branchpro/apps/inference_dash_app.py

Upload serial interval button

---

branchpro/apps/_inference.py
branchpro/apps/inference_dash_app.py

Add loading component

---

branchpro/apps/_simulation.py

Issue 122 simulation app bug

---

branchpro/apps/_dash_app.py
branchpro/posterior.py
branchpro/tests/test_posterior.py

Implement maximum number of samples

---

branchpro/posterior.py

Change type to float32

---

branchpro/apps/_dash_app.py
branchpro/apps/_simulation.py
branchpro/apps/simulation_dash_app.py
branchpro/models.py

Issue 126 imports sim app

---

branchpro/apps/_dash_app.py
branchpro/apps/_inference.py
branchpro/apps/_simulation.py
branchpro/apps/inference_dash_app.py
branchpro/apps/simulation_dash_app.py
setup.py

Create hover objects; still need add correct text

---

README.md
index.html

Closes #187 
I decided to leave out the actual reference until it's more finalized

Issue 187 pages

---

branchpro/data_library/covid_ontario/parse_data.py

193 fix pandas warning

---

Procfile_inference/Procfile
branchpro/__init__.py
branchpro/posterior.py
branchpro/tests/test_posterior.py
docs/source/posterior_distribution.rst
setup.py

My current ideas for cutting cpu and memory usage, in the hope of getting it to run with 1000 serial interval samples on heroku.
closes #195

Issue 195 code optimization

---

index.html

Based on what Lisa told us yesterday

write disclaimer

---

branchpro/apps/_inference.py
branchpro/apps/inference_dash_app.py
setup.py

Solves time-out issue on the branch pro web app when working with 1000 serial intervals.

Separate callbacks

---

branchpro/apps/_inference.py
branchpro/apps/inference_dash_app.py
branchpro/posterior.py
branchpro/tests/test_posterior.py
setup.py

Issue 206 progress bar

---

.github/workflows/check-copyright.yml
.github/workflows/coverage-test.yml
.github/workflows/doctest.yml
.github/workflows/flake8-style-test.yml
.github/workflows/os-unittests.yml
.github/workflows/python-version-unittests.yml
setup.py

The error message in the build of the read the docs says:
"""
RuntimeError: Python version >= 3.9 required.
"""

Issue 231 read te docs

---

branchpro/figures.py
branchpro/tests/test_figures.py
setup.py

https://github.com/SABS-R3-Epidemiology/transmission-heterogeneity-results/pull/19

new mers figure

---

.github/workflows/check-copyright.yml
.github/workflows/coverage-test.yml
.github/workflows/doctest.yml
.github/workflows/python-version-unittests.yml
README.md

Update readme and tests
